name: Lint and Build Docker

on: push

jobs:
  lint:
    name: Lint FastAPI Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Lint with ruff
        run: ruff check . --fix
      # - name: Format code with black
      #   run: black app/
          
      # - name: Lint with flake8
      #   run: flake8 . --max-line-length=200
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-fastapi-app .
        

